apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-issuers
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/sabre1041-backstage-demo/backstage-demo.git
    targetRevision: HEAD
    path: cert-manager/cert-manager-issuers
    helm:
      values: | 
        letsencrypt:
          email: raffaele.spazzoli@gmail.com
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      backoff:
        duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 10m # the maximum amount of time allowed for the backoff strategy
  ignoreDifferences:
  - group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-issuer
    jsonPointers:
    - /spec/acme/solvers        