apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespace-configurations
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/sabre1041-backstage-demo/backstage-demo.git
    targetRevision: HEAD
    path: namespace-configurations
    directory:
      include: "*.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 10m # the maximum amount of time allowed for the backoff strategy 